name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 11 * * Tue

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with: 
          merge_method: squash 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
