name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # https://crontab.guru/every-hour
    #- cron: 0 11 * * Tue
    - cron: 0,5,10,15,20,25 * * * Mon

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with: 
          merge_method: squash 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
